### ISSUE TITLE
Failure to load & visualise data in GUI on Mac OS X

### ISSUE THREAD

**Issue by joramvanrheede** [flatironinstitute/qt-mountainview#1]
[This is my first issue submission - I am not quite sure of the etiquette for these on github but I am hoping that it is helpful for me to report an issue I have encountered trying to make this work]

I'm currently test-driving mountainlab-js on Mac OS X (High Sierra v10.13.4), which appears to be working fine (I can sort example data as well as converted openephys .continuous dat, visualise results using matplotlib and use 'firings.mda' file for further analysis). I am now trying to get qt-mountainview to work and encountered the following issue - The GUI opens fine but the fields where I should see data are empty. This happens both with the mountainsort example data (following the example from: https://mountainsort.readthedocs.io/en/latest/) and with my own openephys data after converting to mda and sorting.

Command and full sequence of output:

"
qt-mountainview --raw=data/raw.mda.prv --firings=data/firings.mda.prv --geom=data/geom.csv --samplerate=30000

Setting up object registry...
Parsing command-line parameters...
Creating MVContext...
Setting up context...
Setting up main window...
Adding controls to main window...
Opening initial views...
Starting event loop...

  error: unknown option `--iops'

":::: Failed to open DiskReadMda32 file: /tmp/mountainlab-tmp/tmp_long_term/5697795064b86632d911ed9b760483ad8d00d5a6_templates_out.tmp"
"File does not exist: /tmp/mountainlab-tmp/tmp_long_term/5697795064b86632d911ed9b760483ad8d00d5a6_templates_out.tmp"
Unable to read chunk of templates in cluster detail view
"

I do have a /tmp/mountainlab-tmp/tmp_long_term/ directory which appears to have been created by qt-mountainview, but there are no files in it. 

I'm not sure how to further trace back the 'error: unknown option '--iops''.

I appreciate this software is still a work in progress, so this is more of an FYI for the ongoing development in case this hasn't come up on any of your machines.

**Comment by magland** [comment]
Thanks Joram for the report. The --iops error makes me thing you may not have the latest version of mountainlab-js. Could you try to pull the latest version of that software?

**Comment by joramvanrheede** [comment]
Hi Jeremy,
Thank you for the very fast reply, I hadn't realised there was an updated version of mountainlab-js already (I only pulled and installed it for the first time last week)! This does resolve the issue - I can now load and visualise example data and there are no errors.
Thank you for your work creating such powerful tools for the neuroscience community, and apologies for the rookie mistake!
Joram

**Comment by magland** [comment]
No need to apologize. Such comments are very helpful... and thanks for being patient as we continue to work out the optimal way to package the software.
J
