### ISSUE TITLE
Some views fail to display

### ISSUE THREAD

**Issue by jchutrue** [flatironinstitute/qt-mountainview#4]
I set up a conda environment and installed qt-mountainview with `conda install -c flatiron qt-mountainview`. When I launched it, I couldn't view the cross-correlograms between clusters:
![selection_058](https://user-images.githubusercontent.com/14321886/47031181-fdb80400-d134-11e8-94ce-783566eebb95.png)

Here is the output of the command I executed:
![selection_056](https://user-images.githubusercontent.com/14321886/47031232-132d2e00-d135-11e8-824c-3cb332889b97.png)
![selection_057](https://user-images.githubusercontent.com/14321886/47031244-16281e80-d135-11e8-8dd7-29008c50d0da.png)

**Comment by tjd2002** [comment]
It seems to be complaining about the processor not being able to find Qt (which doesn't make a ton fo sense since MountainView is itself a Qt app.

Requests:
1) Can you paste the output above as a code block (i.e. as text, not a screenshot)
2) Can you paste in the output from `ml-config` and `ml-list-processors`?

**Comment by tjd2002** [comment]
In particular, it looks like it is loading some processors from: 
`/home/jchu/code/mountainlab/packages`
and not from somewhere within the conda env: 
`/home/jchu/applications/anaconda3/envs/ms4/`

Maybe because you configured your conda package search path manually to include that first directory.

**Comment by jchutrue** [comment]
You are right, there were some paths I added to the PATH variable. I removed those; here is the updated output: 
[qt-mountainview.txt](https://github.com/flatironinstitute/qt-mountainview/files/2484065/qt-mountainview.txt)
[ml-config.txt](https://github.com/flatironinstitute/qt-mountainview/files/2484068/ml-config.txt)
[ml-list-processors.txt](https://github.com/flatironinstitute/qt-mountainview/files/2484070/ml-list-processors.txt)
I didn't add a conda package search path as far as I know. But with various versions of mountainlab/mountainsort on my machine, maybe it's time to wipe those.

**Comment by tjd2002** [comment]
Sorry that was a typo, I meant "mountainlab package search" path, not "conda package search path".

However according to those logs qt-mountainview is still trying to load processors from `/home/jchu/code/mountainlab/packages`:
```
[ Getting processor spec... ]
Error running: /home/jchu/code/franklab_mstaggedcuration/python/tagged_curation.mp spec
[...]
Error running: /home/jchu/code/mountainlab/packages/mountainsort/packages//ms3/bin/ms3.mp spec
[...]
Error running: /home/jchu/code/msdrift/python/drift.mp spec
[...]
Error running: /home/jchu/code/mountainlab/packages/mountainsort/packages//mountainsortalg/bin/mountainsortalg.mp spec
```
I'm at a loss to know where it could be getting that path from; I don't think there's any reason that qt-mountainview (installed via conda) would know to look there unless it had been configured to look there somehow.

1) Do you have a ~/.mountainlab directory? Does it contain a mountainlab.env file? If so what is the contents of that file?

Can you check a couple more things (with your conda env activated):
2) output of `echo $PATH`
3) output of `which -a qt-mountainview`
4) output of `which -a ml-config`

**Comment by jchutrue** [comment]
Hope you don't mind if I paste the output directly instead of uploading a bunch of text files
1. Yes I do; it looks like this:
ML_TEMPORARY_DIRECTORY=/home/jchu/DataStorage
ML_ADDITIONAL_PACKAGE_SEARCH_DIRECTORIES=/home/jchu/code/mountainlab/packages/mountainsort/packages/:/home/jchu/code/franklab_mstaggedcuration:/home/jchu/code/msdrift

2. `echo $PATH` /home/jchu/applications/anaconda3/envs/ms4/bin:/home/jchu/applications/Qt/5.9.1/gcc_64/bin:/home/jchu/applications/anaconda3/bin:/home/jchu/bin:/home/jchu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin://home/jchu/bin

3. `which -a qt-mountainview`
/home/jchu/applications/anaconda3/envs/ms4/bin/qt-mountainview

4. `which -a ml-config`
/home/jchu/applications/anaconda3/envs/ms4/bin/ml-config

For what it's worth I removed the ~/.mountainlab/mountainlab.env file, and that got rid of the errors. But I still cannot view the cross-correlograms.

**Comment by jchutrue** [comment]
Also tried removing the path to my Qt 5.9.1 installation. No luck yet.

**Comment by tjd2002** [comment]
Try removing your ~/.mountainlab/mountainlab.env file

If that fixes it, then there’s a bug in qt-mountainview; it should ignore that file if it’s installed by conda.

**Comment by jchutrue** [comment]
That got rid of the error messages...the cross-correlograms still don't display though

**Comment by tjd2002** [comment]
Gah! Guess those warnings were a red herring.

At this point I’ll ask @magland to weigh in here about whether cross-correlograms should be working. 

I’ll also double-check that they’re working in my hands.

**Comment by jchutrue** [comment]
Thanks! I'd be happy to share the data I was analyzing with you as well

**Comment by magland** [comment]
Cross-correlograms should be working. And qt-mountainview should have all the processors built in inside itself, so I am not sure why you are getting the problem. Did you pass the samplerate parameter into mountainview?

**Comment by jchutrue** [comment]
I see I am missing the samplerate flag. Everything is working now.

**Comment by tjd2002** [comment]
You aren’t the first person to have an issue with this. We should at least warn users when it’s missing, and possibly make it mandatory
